### ISSUE TITLE
:VimLatexCompileToggle followed by :VimLatexView opens yet another mupdf window

### ISSUE THREAD

**Issue by Konfekt** [lervag/vim-latex#111]
If mupdf is used as a viewer, then

`:VimLatexCompileToggle | VimLatexView<cr>` 

opens two mupdf windows and only the last is synced (by synctex). 

Can you verify that? 

It works fine if `VimLatexRSearch` is used instead of `VimLatexView`.

The the window is synced and `VimLatexView` afterwards does not open a new instance.

**Comment by Konfekt** [comment]
Closing for now as suddenly disapeareed.

**Comment by lervag** [comment]
The mupdf window ID is retrieved after the first callback when `VimLatexCompileToggle` has been issued. If the compilation is not successful or for some reason does not create a pdf, then this callback will not be able to set an ID. Latexmk will still open the pdf when the pdf becomes available, without setting the ID. This particular problem is a little bit difficult to fix, at least I don't see a good solution.

So the issue here is reproducible in some cases, but I don't know how to improve the system as of yet.

**Comment by Konfekt** [comment]
Hmm.. now, when trying to open mupdf such that it syncs to Vim, I need to open it three times and close the two previously openend mupdf windows. 

Perhaps adding a second of `sleep` before catching the mupdf ID, as before, could aleviate this problem?

**Comment by lervag** [comment]
I've actually removed the `sleep`. I did that at the same time as I moved the entire mupdf ID catching code to the callback function, which should not need the sleep. In addition, the sleep made vim unresponsive, since vim is not asynchronuous.

However, since the ID catcher is now in the callback, a sleep should not interfere with vim directly. You could check if your problem is fixed by adding a sleep above line 95 in `latexmk.vim`. It does not really feel like a good fix, though.
