### ISSUE TITLE
vi$ fails inside of escaped braces for displayed math

### ISSUE THREAD

**Issue by Konfekt** [lervag/vim-latex#115]
Let `test.tex` be
```
\[
  \{$\theta$\}
\]
```
and  `.vimrc` contains
```
  xnoremap <silent><buffer> i$ :<c-u>call latex#motion#sel_inline_math(1)<cr>
```
Expected: If the cursor is on `$\theta$` then `vi$` higlights `\theta`.

**Comment by lervag** [comment]
Interesting. The reason this breaks is because we use the current syntax element to detect whether or not we are inside a pair of `$`s. In particular, we identify such areas with `texMathZoneX`. In the given case, we are already inside a different math environment, `texMathZoneW`, thus the function does not do anything.

The interesting part is: Why do you use the dollars in this case? The `\[` and `\]` designate a math environment already?

**Comment by Konfekt** [comment]
Good question. Before turning into a mininal example, I stumbled on it by 
```
\[\{\text{ all points $x$ that ... } \}\]
```

**Comment by lervag** [comment]
Yes, but in this case it works. At least it does for
```tex
\[ \{ \text{for $\theta$ in tested} \} \]
```

**Comment by Konfekt** [comment]
Ok. It was my erroneous escaping then. 

I simply did not expect that `vi$` depended on the correct TeX syntax but only checked if the pair itself has an opening and closing marker `$`.

**Comment by lervag** [comment]
I've found the current implementation (which is adopted from LaTeX-Box) to be pretty good. I've not experienced it to fail as of yet, except in the case you mentioned in the first post. But as I argued I don't think that case is good LaTeX code anyways.
