### ISSUE TITLE
Consider to use custom `latexmkrc` file for mupdf viewer

### ISSUE THREAD

**Issue by lervag** [lervag/vim-latex#119]
When we use the `mupdf` viewer, we should set some `latexmk` options in addition to those used in general. This might be best done by using a specific and custom latexmkrc file.

**Comment by Konfekt** [comment]
Ah, as far as I can see that's only necessary for viewers that natively support inverse search such as Zathura to pass on the command string with which gVim/Vim has to be called. 

Regarding the example Zathura, with
```
let g:latex_view_general_options = shellescape("-s -x '" . exepath(v:progpath) . " --servername " . v:servername . " +{%line} {%input}'")
```
alone, Zathura will only know how to inverse search when started from Vim. When started from LatexMk, at least the option
```
$pdf_previewer = "zathura -s -x 'gvim +{%line} {%input}'";
```
However, this way Zathura, when started by Latexmk, neither knows if it should open Vim or Gvim, nor which instance (=servername).
To make it more coherent,
```
 let g:latex_latexmk_options =
    \ " -e ".shellescape("zathura -s -x '" . exepath(v:progpath) . " --servername " . v:servername . " +{%line} {%input}';")
```
should go along with the above `g:latex_view_general_options`.

**Comment by nasenatmer** [comment]
IMHO we should only put settings into an internal `latexmkrc` that can't be done easily with `vim-latex`.

With some things (like automatically opening the pdf previewer after successful compilation) it would make sense to document all the possibilities for users who prefer to use latexmk more heavily, but leaving the choice always seems like a good idea?!

And as such I think that it is rather for viewers such as `mupdf` that don't support backwards-search natively to introduce those settings, while for `zathura` as long as it is invoked by `\lv`, it's not really necessary to include an additional `latexmkrc` and it should be preferred to use `vim-latex` settings as far as possible.

To document all the useful things that @Konfekt listed already which should allow to do much of mupdf-specific config with `latexmk`
```sh
# Set pdf viewer as in 'start VIEWER'
$pdf_previewer = 'start mupdf';

# If zero, check for a previously running previewer on the same file and update it.  If nonzero, always start a new previewer.
$new_viewer_always = 0;

# How to make the PDF viewer update its display when the PDF file changes.  See the man page for a description of each method.
$pdf_update_method = 2;

# When PDF update method 2 is used, the number of the Unix signal to send
$pdf_update_signal = 'SIGHUP';
```

**Comment by lervag** [comment]
@Konfekt @nasenatmer 
I'm pushing an update quite soon where I've attached an option argument inject function from `latex#view#append_latexmk_arguments()` to `s:latexmk_build_cmd(data)` (in `latexmk.vim`). This new function will inject the necessary arguments to latexmk for starting the previewer with the desired options, so that one does not need to have this in ones `.latexmkrc` file. It seems to work quite well, but I have one question: Which options should be used for `zathura` (except for the `$pdf_previewer`, which I already know)?

**Comment by nasenatmer** [comment]
I think you can clearly leave out `$pdf_update_method` as zathura detects file updates automatically. Therefore, `$pdf_update_signal` should also be superfluous.

On the other hand, `$new_viewer_always` could be quite handy. If it could prevent `\lv` from opening ever more instances of zathura that would be perfect though I didn't get it to work here (but that might be due to still active xdotools…)

PS: from the latexmk manual (regarding the `$pdf_previewer` option):
> **Important note**: Normally you will want to have a previewer run detached, so that latexmk
doesn’t wait for the previewer to terminate before continuing its work. So normally you should
prefix the command by "start ", which flags to latexmk that it should do the detaching of the pre-
viewer itself (by whatever method is appropriate to the operating system). **But sometimes letting
latexmk do the detaching is not appropriate (for a variety of non-trivial reasons), so you should put
the "start " bit in yourself, whenever it is needed.**

I'm not sure what these non-trivial reasons are, but as zathura has a `--fork` parameter it seems sensible to leave away the `start` bit and use zathura's function like this: `$pdf_previewer = 'zathura --fork';`

**Comment by lervag** [comment]
Good point, thanks! I agree to keep the `$new_viewer...`, although I was not able to find a case where this actually worked as expected...

**Comment by lervag** [comment]
My last updates closes this issue.
