### ISSUE TITLE
Input on difference between mupdf and zathura

### ISSUE THREAD

**Issue by lervag** [lervag/vim-latex#121]
@Konfekt @nasenatmer It seems you guys are using zathura now, and I am a little bit curious: Except for inverse search, which seems to work well, what do you find better in zathura?

**Comment by nasenatmer** [comment]
For me it's partly historical reasons: I stumbled upon zathura before I found mupdf.

Other than that, I stay with zathura due to its extensive customisability. This is especially important for me as I'm not using a qertz/y standard keyboard and therefore, the vim keys don't make sense and I have to remap most of them. You can see that in my [`zathurarc`](https://github.com/nasenatmer/dotfiles-bone2/blob/master/zathurarc).

Additionally, I prefer smooth scrolling instead of page-wise only. And zathura's `toc` feature (press TAB to switch to toc) is quite nice, too, especially when using the `biblatex` manual :)

**Comment by lervag** [comment]
Thanks. Just curious: What do you mean with "especially when using the `biblatex` manual"? Is it a big manual for which the TOC is very useful?

**Comment by nasenatmer** [comment]
Exactly: [265 pages](http://mirrors.ctan.org/macros/latex/contrib/biblatex/doc/biblatex.pdf)  of documentation goodness, well-written and nicely structured.

**Comment by lervag** [comment]
Nice! :)

**Comment by Konfekt** [comment]
Well, I stick to mupdf. Just got too accustomed to inverse searching from vim. @lervag Let me know if you ever switch.

**Comment by lervag** [comment]
I'll be testing out zathura for some time now, I think. I like that it is more customizible, and I agree that the TOC functionality is pretty neat. I've created a configuration that seems to work well, see [here](https://github.com/lervag/dotfiles/blob/master/config/zathura/zathurarc).

I might switch from mupdf if I don't find any reason not to.

**Comment by Konfekt** [comment]
Ok. I never compared `mupdf` to anything but saw some whining that there is no counterpart to SumatraPDF on Linux, though mupdf came next to it; other viewers were too slow.

**Comment by lervag** [comment]
I've heard similar. I've been happy with mupdf, though. But zathura seems to be fast as well, and allows more customizations and some more features.
