### ISSUE TITLE
delete/change surrounding command

### ISSUE THREAD

**Issue by kiryph** [lervag/vim-latex#97]
I really like following mappings of your plugin
`dse` - delete surrounding environment
`cse` - change surrounding environment

Could you add something like this:
`dsc` - delete surrounding command, e.g.  `\textbf{not important} -> not important`
`csc` - change surrounding command, e.g. `\textit{important} -> \textbf{important}`

However, `dse/cse` and `dsc/csc` overwrite tpope/surround commands `ds` and `cs` which I consider as essential for vim.

Is it possible to hand over to surround.vim if the third pressed letter is not an `e`/`c`?

Note, surround.vim has already the normal mode  mapping `ys<textobject/motion>l` and the visual mode mapping `Sl` to surround with a latex environment. Instead of `l` the backslash `\` can be used.
This can be extended for commands by setting up the letter `c` by
`let g:surround_99 = "\\\1command: \1{\r}"`

Unfortunately, surround.vim does not allow to customize `surround-targets` only `surround-replacements`. This means `cs` or `ds` of surround.vim do not work symmetrically as expected.

**Comment by lervag** [comment]
Thansk for the suggested additions, I think they look both interesting and useful. However, I have a lot off stuff going on at the moment, so I will not give it priority right now. I took the liberty of opening a new issue for this request so I can address the remaining part of your issue here.

When it comes to your comment that `dse/cse` overwrites `surround.vim`, then I have to disagree. I use `surround.vim` very actively (which is exactly why I was inspired to add the `dse/cse` commands), and I do not have the problem you specify here. That is, for me the mapping hands over to `surround.vim` if the third letter is not an `e/c`. So, could you please create a minimal working example (minimal tex file) with a minimal vimrc file that only loads `vim-latex` and `surround.vim` (you may use my [minivimrc](https://github.com/lervag/dotvim/blob/master/minivimrc) as a minimal vimrc template) in order to make it possible for me to reproduce your issue?

I think I actually tried to implement the `cse/dse` commands through `surround.vim` once, and I think that I ended up with the conclusion that it was either not possible, or it was too difficult. Based on your comment it seems I remember correctly, that it is not possible to customize the `surround-targets`.

**Comment by kiryph** [comment]
Sorry for my comment about overriding surround mappings. I had a problem with a different plugin.
Great to see it working.

**Comment by lervag** [comment]
Great! I'll close my added issue and use this one for the feature request for the new commands `csc` and `dsc`.

**Comment by lervag** [comment]
I've implemented the suggested functionality. Note that the `dsc` depends on `surround.vim`, and will only be available if `surround.vim` is available. Also note that the `csc` is rather simple at the moment. There is probably room for improvement, in particular to handle failures. I'll address such issues later if they arise.
